<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>Valir.Core</PackageId>
        <Description>Core runtime for Valir distributed job queue. Contains WorkerRuntime, RetryPolicy, JobStateMachine, and ValirOptions configuration.</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Valir.Abstractions\Valir.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="System.ComponentModel.Annotations" />
        <PackageReference Include="Microsoft.Extensions.Options" />
        <PackageReference Include="Cronos" />
    </ItemGroup>

</Project>
